// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfhV9__FDT9j-vgtnhTQA-d5uaWwZcL3w',
    appId: '1:166758814774:web:767c46b93c7c9c0b6d3497',
    messagingSenderId: '166758814774',
    projectId: 'chatapp-d0c7d',
    authDomain: 'chatapp-d0c7d.firebaseapp.com',
    storageBucket: 'chatapp-d0c7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW9fsQNWhQ-2NgTLDofELYsii1wyRQbio',
    appId: '1:166758814774:android:9d2b2216ceb984066d3497',
    messagingSenderId: '166758814774',
    projectId: 'chatapp-d0c7d',
    storageBucket: 'chatapp-d0c7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy8sg3HuT3X1ww8xdJigtVqlKVK05UJR8',
    appId: '1:166758814774:ios:7c6a86f5188225e16d3497',
    messagingSenderId: '166758814774',
    projectId: 'chatapp-d0c7d',
    storageBucket: 'chatapp-d0c7d.appspot.com',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy8sg3HuT3X1ww8xdJigtVqlKVK05UJR8',
    appId: '1:166758814774:ios:7c6a86f5188225e16d3497',
    messagingSenderId: '166758814774',
    projectId: 'chatapp-d0c7d',
    storageBucket: 'chatapp-d0c7d.appspot.com',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfhV9__FDT9j-vgtnhTQA-d5uaWwZcL3w',
    appId: '1:166758814774:web:bde82624882155626d3497',
    messagingSenderId: '166758814774',
    projectId: 'chatapp-d0c7d',
    authDomain: 'chatapp-d0c7d.firebaseapp.com',
    storageBucket: 'chatapp-d0c7d.appspot.com',
  );
}
